### ISSUE TITLE
Getting a 'ValueError : unknown url type'

### ISSUE THREAD

**Issue by AceSnipes** [luispadron/BandLoader#1]
Traceback (most recent call last):
  File "main.py", line 227, in run
  File "D:\Programming Projects\Python Projects\BandLoader\BandLoader\bandloader.py", line 168, in download_tracks
  File "C:\Python34\lib\site-packages\wgetter.py", line 268, in download
  File "C:\Python34\lib\urllib\request.py", line 161, in urlopen
  File "C:\Python34\lib\urllib\request.py", line 448, in open
  File "C:\Python34\lib\urllib\request.py", line 266, in **init**
  File "C:\Python34\lib\urllib\request.py", line 292, in full_url
  File "C:\Python34\lib\urllib\request.py", line 321, in _parse
ValueError: unknown url type: '//popplers5.bandcamp.com/download/track?enc=mp3-128&fsig=db9fb174c3fce54d3f4e166f920e9ebc&id=408550971&stream=1&ts=1446826925.0'

**Comment by luispadron** [comment]
Are you on the latest version? I should've have fixed this issue on the latest one because I noticed it. It's an issue with the way I was getting the URL. Let me know what version you're on

**Comment by AceSnipes** [comment]
Yep that's the problem.... had V1.3 not the newest V1.4. My mistake! Everything is now working as it should.
